name: Autocloser
# https://github.com/marketplace/actions/issue-title-checker
on:
  issues:
    types: [opened]
jobs:
  echo_issu_title:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - name: Title name
        run: echo 'The issue title is "' ${{ issue.title }} '"'
        
  autoclose:
    runs-on: ubuntu-latest
    steps:
    - name: Autoclose issues whose title matched the specified regex
      uses: IndyV/IssueChecker@v1.0
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-close-message: "This issue was automatically closed because it has no content"
        issue-pattern: "foo"
